### ISSUE TITLE
Non-members can access restricted forum replies directly

### ISSUE THREAD

**Issue by andrewlimaza** [strangerstudios/pmpro-bbpress#13]
Non-members can access restricted forum replies directly.

i.e. http://mysite.com/forums/reply/51/

**Comment by strangerstudios** [comment]
At some point we added a filter that replaces topic/reply content with this message for users without permission: "Replies viewable by members only"

However, this may not be enough for some sites. They may want to:
* Keep all topics from forums that require membership out of the main feed.
* Disable the RSS feed for forum that requires membership, e.g. /forums/forum-name/feed/
* Restrict access to user profile pages based on membership. This could be a separate setting somewhere.
* Restrict access to tags archives or any other bbpress pages we are forgetting about.

**Comment by andrewlimaza** [comment]
This has been fixed, accessing a topic directly (or via search) that you don't have access to will automatically be redirected/hidden.
