### ISSUE TITLE
New Feature request

### ISSUE THREAD

**Issue by jccompagnon** [strangerstudios/pmpro-bbpress#15]
Hi,
We are trying to have a bbpress with paid membership pro site where we would like the non members to see the forum and the topics. 
BUT only paid members would see the reply

So it would be nice to control membership access to all or certain topics and same with replies. so that all replies are auto set for members.

I could even see letting non paid members post a question but have to register to see the answer.

**Comment by eighty20results** [comment]
Hi,

There is a 3rd party plugin that offers some of these features: https://eighty20results.com/wordpress-plugins/e20r-roles-licenses/

**Comment by andrewlimaza** [comment]
@jccompagnon this is now done by default if a user is able to get access to a restricted forum reply on a topic. I am going to close this ticket.

If you need help with customizing this further, please don't hesitate to reach out.
