### ISSUE TITLE
Administrators cannot access the forums

### ISSUE THREAD

**Issue by amityweb** [strangerstudios/pmpro-bbpress#19]
I installed this but as an administrator I cannot access them. Either all administrators should get access regardless of membership plans, or there is an option to allow administrators.

**Comment by ideadude** [comment]
Even administrators need to have the membership level to access the forums. I agree that this is an odd choice of ours, and I'll think about ways to simply allow admins to access everything while making it clear to admins what is and is not protected.

**Comment by andrewlimaza** [comment]
I know this is pretty late, you may use this gist -> https://gist.github.com/andrewlimaza/823ddff62b8aedafc4d4d6663ab9f695
