### ISSUE TITLE
Call to undefined function when Paid Memberships Pro is deactivated

### ISSUE THREAD

**Issue by kimcoleman** [strangerstudios/pmpro-bbpress#20]
We should do a pass on this add on to ensure that all functions are properly checked so that errors aren't triggered when Paid Memberships Pro is deactivated. Currently throwing an error on line 189: 

Call to undefined function pmpro_getMembershipLevelForUser() in pmpro-bbpress.php on line 189

**Comment by andrewlimaza** [comment]
This has been fixed, we now check that PMPro is activated.
