### ISSUE TITLE
Maybe need a conditional to check if bbPress plugin is installed and active?

### ISSUE THREAD

**Issue by labsecrets** [strangerstudios/pmpro-bbpress#6]
Fatal error: Call to undefined function bbp_get_forum_id() in /home/vmk/public_html/wp-content/plugins/pmpro-bbpress/pmpro-bbpress.php on line 113

Not a big problem because the cause is obvious... but something like this I use in our Child Themes to check for WooCommerce might work?

/*-----------------------------------------------------------------------------------*/
/* Step Two) Check whether WooCommerce is installed - dismissible nag notice etc.----*/
/*-----------------------------------------------------------------------------------*/

if (!class_exists('woocommerce')) {
/* Display a notice that can be dismissed */
add_action('admin_notices', 'lab_woocommerce_admin_notice');
function lab_woocommerce_admin_notice() {
	if ( current_user_can( 'edit_theme_options' ) );
    global $current_user ;
        $user_id = $current_user->ID;
        /* Check that the user hasn't already clicked to ignore the message */
    if ( ! get_user_meta($user_id, 'lab_woocommerce_ignore_notice') ) {
        echo '<div class="updated"><p>';
        printf(__('We recommend you <a href="http://www.woothemes.com/woocommerce/" target="_blank">install and activate the WooCommerce plugin</a> for all of this theme\'s functionality to work | <a href="%1$s">Hide Notice</a>'), '?lab_woocommerce_nag_ignore=0');
        echo "</p></div>";
    	}
	}

add_action('admin_init', 'lab_woocommerce_nag_ignore');
function lab_woocommerce_nag_ignore() {
	if ( current_user_can( 'edit_theme_options' ) );
    global $current_user;
        $user_id = $current_user->ID;
        /* If user clicks to ignore the notice, add that to their user meta */
        if ( isset($_GET['lab_woocommerce_nag_ignore']) && '0' == $_GET['lab_woocommerce_nag_ignore'] ) {
             add_user_meta($user_id, 'lab_woocommerce_ignore_notice', 'true', true);
    	}
	}
} // End class_exists('woocommerce') (line 31 )

	

/**
 * Check if WooCommerce is active
 **/
if ( in_array( 'woocommerce/woocommerce.php', apply_filters( 'active_plugins', get_option( 'active_plugins' ) ) ) ) {
						
// Set path to WooFramework and theme specific functions
$woocommerce_path = get_stylesheet_directory() . '/woocommerce/';

// WooCommerce
require_once ($woocommerce_path . 'theme-install.php' );                        // WooCommerce Install
require_once ($woocommerce_path . 'woocommerce-layout.php' );                   // WooCommerce Layout
require_once ($woocommerce_path . 'woocommerce-functions.php' );                // WooCommerce Functions

} // End woocommerce.php check (line 63 )

**Comment by strangerstudios** [comment]
Latest version will have this. Thanks.
